sp: 
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"abc\"},{\"id\":8, \"username\":\"def\",\"password\":\"def\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"ghi\"},{\"id\":99, \"username\":\"aaa\",\"password\":\"aaa\"}]"   

spring: 
    application:
      name: user-service
    cloud: 
     config:
      override-none: true
      
server:
  port: 8101      
     
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
   
     
management:
  endpoints:
    web:
      exposure:
        include: "*"
     
     